
- name: Check HTML
        uses:chabad360/htmlproofer@master
with:
          directory: "./public"
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer
